name = "loopmaker-updates"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "9da0a3e2fbc6f382f556b4c4c622f6a3"

[[r2_buckets]]
binding = "UPDATES_BUCKET"
bucket_name = "loopmaker-updates"

[[kv_namespaces]]
binding = "APPCAST_KV"
id = "REPLACE_WITH_KV_NAMESPACE_ID"

[vars]
ENVIRONMENT = "production"
